version: '3'
services:
  airflow:
    image: apache/airflow:2.7.1-python3.11
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow:/opt/airflow/src
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./config:/opt/airflow/config
    command: >
      bash -c "pip install confluent-kafka sqlalchemy psycopg2-binary python-dotenv pydantic &&
              echo 'Инсталирани необходими пакети' &&
              ls -la /opt/airflow/src &&
              PYTHONPATH=/opt/airflow airflow standalone"
    networks:
      - default
      - docker_kafka-network

networks:
  default:
    driver: bridge
  docker_kafka-network:
    external: true
