"""Add Twitter models

Revision ID: 09d53b910cdb
Revises: 494ec1d293b0
Create Date: 2025-03-04 21:24:40.292471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d53b910cdb'
down_revision: Union[str, None] = '494ec1d293b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_influencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_automated', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_influencers_username'), 'twitter_influencers', ['username'], unique=True)
    op.create_table('twitter_api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('requests_used', sa.Integer(), nullable=True),
    sa.Column('reset_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], ['twitter_influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_api_usage_date'), 'twitter_api_usage', ['date'], unique=False)
    op.create_table('twitter_influencer_tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('is_manually_added', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], ['twitter_influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_influencer_tweets')
    op.drop_index(op.f('ix_twitter_api_usage_date'), table_name='twitter_api_usage')
    op.drop_table('twitter_api_usage')
    op.drop_index(op.f('ix_twitter_influencers_username'), table_name='twitter_influencers')
    op.drop_table('twitter_influencers')
    # ### end Alembic commands ###
