"""add_is_archived_to_blockchain_tokens

Revision ID: 16ac6bf28ee1
Revises: 94b57bf7acc7
Create Date: 2025-03-08 13:09:00.014775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ac6bf28ee1'
down_revision: Union[str, None] = '94b57bf7acc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_tokens', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_tokens', 'is_archived')
    # ### end Alembic commands ###
